### ISSUE TITLE
Upload using arc and ex_aws causes error

### ISSUE THREAD

**Issue by zlatio** [smpallen99/ex_admin#102]
Hi,
There seems to be a problem with file uploads using arc and ex_aws. I am using the exact same setup as in your demo app and I get the following error:
```
undefined function Plug.Upload.fetch/2 (Plug.Upload does not implement the Access behaviour)
```
I am not sure why this happens but seems like it's the same in your live demo app since if I try to upload something I get "Bad gateway" - I tried to run the demo app on my local as well - same thing.

Do you have a clue why this happens ?

**Comment by smpallen99** [comment]
@zlatio Not sure what your issue is. Here is my mix.lock file from the server:
```
%{"arc": {:hex, :arc, "0.5.1"},
  "arc_ecto": {:hex, :arc_ecto, "0.3.2"},
  "calliope": {:hex, :calliope, "0.4.0"},
  "certifi": {:hex, :certifi, "0.4.0"},
  "connection": {:hex, :connection, "1.0.2"},
  "cowboy": {:hex, :cowboy, "1.0.4"},
  "cowlib": {:hex, :cowlib, "1.0.2"},
  "csvlixir": {:hex, :csvlixir, "1.0.0"},
  "db_connection": {:hex, :db_connection, "0.2.5"},
  "decimal": {:hex, :decimal, "1.1.2"},
  "ecto": {:hex, :ecto, "1.1.5"},
  "ex_admin": {:git, "https://github.com/smpallen99/ex_admin.git", "51066b8705d56bfac08b59883e1124701a14ba44", [branch: "themes"]},
  "ex_aws": {:hex, :ex_aws, "0.4.18"},
  "ex_form": {:git, "https://github.com/smpallen99/ex_form.git", "6d08d449b112f89e48279daeca74b2b42a16fdda", []},
  "ex_queb": {:hex, :ex_queb, "0.1.2"},
  "exactor": {:hex, :exactor, "2.2.0"},
  "factory_girl_elixir": {:hex, :factory_girl_elixir, "0.1.1"},
  "faker": {:hex, :faker, "0.6.0"},
  "fs": {:hex, :fs, "0.9.2"},
  "gettext": {:hex, :gettext, "0.10.0"},
  "hackney": {:hex, :hackney, "1.5.2"},
  "httpoison": {:hex, :httpoison, "0.8.2"},
  "idna": {:hex, :idna, "1.1.0"},
  "inflex": {:hex, :inflex, "1.5.0"},
  "metrics": {:hex, :metrics, "1.0.1"},
  "mimerl": {:hex, :mimerl, "1.0.2"},
  "number": {:hex, :number, "0.4.1"},
  "phoenix": {:hex, :phoenix, "1.1.4"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "2.0.1"},
  "phoenix_haml": {:hex, :phoenix_haml, "0.2.1"},
  "phoenix_html": {:hex, :phoenix_html, "2.5.1"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.3"},
  "plug": {:hex, :plug, "1.1.2"},
  "poison": {:hex, :poison, "1.5.2"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.11.1"},
  "ranch": {:hex, :ranch, "1.2.1"},
  "scrivener": {:hex, :scrivener, "1.1.4"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.6"},
  "xain": {:hex, :xain, "0.5.2"}}
```
The project is a clone of master. 

Here is the startup script I use to start the application:
```
AWS_ACCESS_KEY_ID=sorry_thats_private AWS_SECRET_ACCESS_KEY=sorry_thats_private MIX_ENV=prod PORT=8080 mix phoenix.server &
```

**Comment by zlatio** [comment]
Does it work on your server? I tried creating new project but got 500 bad gateway so I assume it have the same issue.

**Comment by smpallen99** [comment]
I just tried on http://demo.exadmin.info and I got a bad gateway. However, it work on my local dev machine (mac). I guess I will have to trouble shoot. Here is the mix.lock on my dev machine:

```
%{"arc": {:hex, :arc, "0.5.1"},
  "arc_ecto": {:hex, :arc_ecto, "0.3.2"},
  "calliope": {:hex, :calliope, "0.4.0"},
  "certifi": {:hex, :certifi, "0.4.0"},
  "connection": {:hex, :connection, "1.0.2"},
  "cowboy": {:hex, :cowboy, "1.0.4"},
  "cowlib": {:hex, :cowlib, "1.0.2"},
  "csvlixir": {:hex, :csvlixir, "1.0.0"},
  "db_connection": {:hex, :db_connection, "0.2.5"},
  "decimal": {:hex, :decimal, "1.1.2"},
  "ecto": {:hex, :ecto, "1.1.5"},
  "ex_admin": {:git, "https://github.com/smpallen99/ex_admin.git", "85669f81468f27b85f5297fe0a737ce9da54e876", [branch: "themes"]},
  "ex_aws": {:hex, :ex_aws, "0.4.18"},
  "ex_form": {:git, "https://github.com/smpallen99/ex_form.git", "6d08d449b112f89e48279daeca74b2b42a16fdda", []},
  "ex_queb": {:hex, :ex_queb, "0.1.2"},
  "exactor": {:hex, :exactor, "2.2.0"},
  "factory_girl_elixir": {:hex, :factory_girl_elixir, "0.1.1"},
  "faker": {:hex, :faker, "0.6.0"},
  "fs": {:hex, :fs, "0.9.2"},
  "gettext": {:hex, :gettext, "0.10.0"},
  "hackney": {:hex, :hackney, "1.5.2"},
  "httpoison": {:hex, :httpoison, "0.8.2"},
  "idna": {:hex, :idna, "1.1.0"},
  "inflex": {:hex, :inflex, "1.5.0"},
  "metrics": {:hex, :metrics, "1.0.1"},
  "mimerl": {:hex, :mimerl, "1.0.2"},
  "number": {:hex, :number, "0.4.1"},
  "phoenix": {:hex, :phoenix, "1.1.4"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "2.0.1"},
  "phoenix_haml": {:hex, :phoenix_haml, "0.2.1"},
  "phoenix_html": {:hex, :phoenix_html, "2.5.1"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.3"},
  "plug": {:hex, :plug, "1.1.2"},
  "poison": {:hex, :poison, "1.5.2"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.11.1"},
  "ranch": {:hex, :ranch, "1.2.1"},
  "scrivener": {:hex, :scrivener, "1.1.4"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.6"},
  "xain": {:hex, :xain, "0.5.3"}}
```

**Comment by zlatio** [comment]
Thanks a lot l. I'll try to narrow down what causes the issue.

**Comment by smpallen99** [comment]
I just got it working on http://demo.exadmin.info. Turns out that I did not have ImageMagick installed on that server. I noticed in the exception that it could not find executable `convert`. `which convert` should return the path if you have it installed.

**Comment by erikmueller** [comment]
I have the same error on a local test installation

```
[info] POST /admin/slides
[debug] Processing by ExAdmin.AdminController.create/2
  Parameters: %{"_csrf_token" => "KCBdfTc4BB4eMQc5Pk0ccENbIiEBNgAAjc0EOjhfgUVHK+N9zbxevw==", "commit" => "Create Slide", "resource" => "slides", "slide" => %{"asset_file_name" => %Plug.Upload{content_type: "image/jpeg", filename: "DSC01095.JPG", path: "/var/folders/p6/cg9h2zss01qglq95qxtwy4fh0000gn/T//plug-1466/multipart-549666-685281-1"}, "description" => "desc", "duration" => "1000", "name" => "name"}, "utf8" => "✓"}
  Pipelines: [:browser]
[error] %UndefinedFunctionError{arity: 2, function: :fetch, module: Plug.Upload, reason: "Plug.Upload does not implement the Access behaviour"}
[info] Sent 500 in 147ms
[error] #PID<0.437.0> running Edmin.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /admin/slides
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function Plug.Upload.fetch/2 (Plug.Upload does not implement the Access behaviour)
        (plug) Plug.Upload.fetch(%Plug.Upload{content_type: "image/jpeg", filename: "DSC01095.JPG", path: "/var/folders/p6/cg9h2zss01qglq95qxtwy4fh0000gn/T//plug-1466/multipart-549666-685281-1"}, :file_name)
        (elixir) lib/access.ex:119: Access.fetch/2
        (elixir) lib/access.ex:150: Access.get/3
        (ex_admin) lib/ex_admin/form.ex:818: ExAdmin.Form.build_control/7
        (ex_admin) lib/ex_admin/themes/admin_lte2.ex:40: ExAdmin.Theme.AdminLte2.wrap_item_type/5
        (ex_admin) lib/ex_admin/themes/admin_lte2/form.ex:72: ExAdmin.Theme.AdminLte2.Form.theme_wrap_item/8
        (ex_admin) lib/ex_admin/form.ex:566: ExAdmin.Form.wrap_item/8
        (ex_admin) lib/ex_admin/form.ex:765: anonymous fn/6 in ExAdmin.Form.build_item/5
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_admin) lib/ex_admin/form.ex:764: anonymous fn/5 in ExAdmin.Form.build_item/5
        (ex_admin) lib/ex_admin/themes/admin_lte2/form.ex:122: ExAdmin.Theme.AdminLte2.Form.form_box/3
        (ex_admin) lib/ex_admin/form.ex:513: anonymous fn/6 in ExAdmin.Form.build_main_block/4
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_admin) lib/ex_admin/form.ex:512: ExAdmin.Form.build_main_block/4
        (ex_admin) lib/ex_admin/themes/admin_lte2/form.ex:25: ExAdmin.Theme.AdminLte2.Form.build_form/5
        (ex_admin) web/controllers/admin_controller.ex:240: ExAdmin.AdminController.create/2
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (edmin) lib/phoenix/router.ex:261: Edmin.Router.dispatch/2
        (edmin) web/router.ex:1: Edmin.Router.do_call/2
```
I think I'm just missing sth or doing something wrong since Im pretty new to the whole eco system. 
It happens during a POST request (uploading an image, as the log says)
Anyone any ideas?

Thanks.

**Comment by smpallen99** [comment]
@erikmueller can you post your mix.lock file please.

**Comment by erikmueller** [comment]
sure

```
%{"arc": {:hex, :arc, "0.5.3", "2bc1b4ce8c1064ae12015f5612f3e3853d354859905bb34088b3579bf34a519d", [:mix], [{:httpoison, "~> 0.7", [hex: :httpoison, optional: true]}, {:poison, "~> 1.2 or ~> 2.0", [hex: :poison, optional: true]}, {:ex_aws, "~> 0.4.10 or ~> 0.5.0", [hex: :ex_aws, optional: true]}]},
  "arc_ecto": {:hex, :arc_ecto, "0.3.2", "8893135fe4d5cf9b2a6aeb0e17bedd5c6f7ad5d89f760995805451c859bf8f89", [:mix], [{:ecto, ">= 0.10.0", [hex: :ecto, optional: false]}, {:arc, "~> 0.2", [hex: :arc, optional: false]}]},
  "connection": {:hex, :connection, "1.0.3", "3145f7416be3df248a4935f24e3221dc467c1e3a158d62015b35bd54da365786", [:mix], []},
  "cowboy": {:hex, :cowboy, "1.0.4", "a324a8df9f2316c833a470d918aaf73ae894278b8aa6226ce7a9bf699388f878", [:rebar, :make], [{:cowlib, "~> 1.0.0", [hex: :cowlib, optional: false]}, {:ranch, "~> 1.0", [hex: :ranch, optional: false]}]},
  "cowlib": {:hex, :cowlib, "1.0.2", "9d769a1d062c9c3ac753096f868ca121e2730b9a377de23dec0f7e08b1df84ee", [:make], []},
  "csvlixir": {:hex, :csvlixir, "1.0.0", "e9fd30abfca2d312390060e86bb7ec52487c813824dcccad45bb13e85ecad6b1", [:mix], []},
  "db_connection": {:hex, :db_connection, "1.0.0-rc.2", "c5b2329651ef046d85e47ec2c947cb0e3d10a69eb49fdb71e365e72d6758e4c5", [:mix], [{:sbroker, "~> 1.0.0-beta.2", [hex: :sbroker, optional: true]}, {:poolboy, "~> 1.5", [hex: :poolboy, optional: true]}, {:connection, "~> 1.0.2", [hex: :connection, optional: false]}]},
  "decimal": {:hex, :decimal, "1.1.2", "79a769d4657b2d537b51ef3c02d29ab7141d2b486b516c109642d453ee08e00c", [:mix], []},
  "ecto": {:hex, :ecto, "1.1.8", "0f0348e678fa5a450c266d69816808f97fbd82ade32cf88d4b09bbe8f8c27545", [:mix], [{:sbroker, "~> 0.7", [hex: :sbroker, optional: true]}, {:postgrex, "~> 0.11.0", [hex: :postgrex, optional: true]}, {:poolboy, "~> 1.4", [hex: :poolboy, optional: false]}, {:poison, "~> 1.0 or ~> 2.0", [hex: :poison, optional: true]}, {:mariaex, "~> 0.5.0 or ~> 0.6.0", [hex: :mariaex, optional: true]}, {:decimal, "~> 1.0", [hex: :decimal, optional: false]}]},
  "ex_admin": {:hex, :ex_admin, "0.7.6", "8ea0b7d21a073bd901edf37a10808a0c504d9bd952e41b19cb78a896ab253c00", [:mix], [{:xain, "~> 0.5.3", [hex: :xain, optional: false]}, {:scrivener, "~> 1.0", [hex: :scrivener, optional: false]}, {:phoenix_html, "~> 2.5", [hex: :phoenix_html, optional: false]}, {:phoenix_ecto, "~> 2.0", [hex: :phoenix_ecto, optional: false]}, {:phoenix, "~> 1.1", [hex: :phoenix, optional: false]}, {:inflex, "~> 1.5", [hex: :inflex, optional: false]}, {:factory_girl_elixir, "~> 0.1.1", [hex: :factory_girl_elixir, optional: false]}, {:exactor, "~> 2.2.0", [hex: :exactor, optional: false]}, {:ex_queb, "~> 0.1", [hex: :ex_queb, optional: false]}, {:ecto, "~> 1.1", [hex: :ecto, optional: false]}, {:decimal, "~> 1.0", [hex: :decimal, optional: false]}, {:csvlixir, "~> 1.0.0", [hex: :csvlixir, optional: false]}, {:cowboy, "~> 1.0", [hex: :cowboy, optional: false]}]},
  "ex_queb": {:hex, :ex_queb, "0.1.2", "a7bea897c490875a716042675cec4013b5075de083c26ec1b7f0e0fb5144f5a1", [:mix], [{:ecto, "~> 1.1", [hex: :ecto, optional: false]}]},
  "exactor": {:hex, :exactor, "2.2.0", "2a7418b82d974fe8276edd62c1facf4a9dc06339cdf11b5dcd10359e107fe5c3", [:mix], []},
  "factory_girl_elixir": {:hex, :factory_girl_elixir, "0.1.1", "2c2b41111a409cf74131cd0f651fe65d77eb60d4b45775192ecde9820dc59ac5", [:mix], []},
  "fs": {:hex, :fs, "0.9.2", "ed17036c26c3f70ac49781ed9220a50c36775c6ca2cf8182d123b6566e49ec59", [:rebar], []},
  "gettext": {:hex, :gettext, "0.11.0", "80c1dd42d270482418fa158ec5ba073d2980e3718bacad86f3d4ad71d5667679", [:mix], []},
  "inflex": {:hex, :inflex, "1.6.0", "2c0c9928cd865e3b47cfaaa15c3520dfdb8c6ba5829d036296deb766f2aba770", [:mix], []},
  "phoenix": {:hex, :phoenix, "1.1.6", "7bf19002669c8f692f5a9c8d30dab7b49f3dc56228d5bde92a12fb426b4783c2", [:mix], [{:poison, "~> 1.5 or ~> 2.0", [hex: :poison, optional: false]}, {:plug, "~> 1.0", [hex: :plug, optional: false]}, {:cowboy, "~> 1.0", [hex: :cowboy, optional: true]}]},
  "phoenix_ecto": {:hex, :phoenix_ecto, "2.0.2", "1aff51d1cd21cc39d7891cae2284399cbf4b8e32fb7864e68f5d272d2934e48a", [:mix], [{:poison, "~> 1.3 or ~> 2.0", [hex: :poison, optional: true]}, {:phoenix_html, "~> 2.2", [hex: :phoenix_html, optional: true]}, {:ecto, "~> 1.1.2", [hex: :ecto, optional: false]}]},
  "phoenix_html": {:hex, :phoenix_html, "2.6.0", "b9f7e091eb3d908586d9634596478fb9e577ee033d76f4ff327a745569bdd2d8", [:mix], [{:plug, "~> 0.13 or ~> 1.0", [hex: :plug, optional: false]}]},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.5", "829218c4152ba1e9848e2bf8e161fcde6b4ec679a516259442561d21fde68d0b", [:mix], [{:phoenix, "~> 1.0 or ~> 1.2-rc", [hex: :phoenix, optional: false]}, {:fs, "~> 0.9.1", [hex: :fs, optional: false]}]},
  "plug": {:hex, :plug, "1.1.6", "8927e4028433fcb859e000b9389ee9c37c80eb28378eeeea31b0273350bf668b", [:mix], [{:cowboy, "~> 1.0", [hex: :cowboy, optional: true]}]},
  "poison": {:hex, :poison, "2.2.0", "4763b69a8a77bd77d26f477d196428b741261a761257ff1cf92753a0d4d24a63", [:mix], []},
  "poolboy": {:hex, :poolboy, "1.5.1", "6b46163901cfd0a1b43d692657ed9d7e599853b3b21b95ae5ae0a777cf9b6ca8", [:rebar], []},
  "postgrex": {:hex, :postgrex, "0.11.2", "139755c1359d3c5c6d6e8b1ea72556d39e2746f61c6ddfb442813c91f53487e8", [:mix], [{:connection, "~> 1.0", [hex: :connection, optional: false]}, {:db_connection, "~> 1.0-rc", [hex: :db_connection, optional: false]}, {:decimal, "~> 1.0", [hex: :decimal, optional: false]}]},
  "ranch": {:hex, :ranch, "1.2.1", "a6fb992c10f2187b46ffd17ce398ddf8a54f691b81768f9ef5f461ea7e28c762", [:make], []},
  "scrivener": {:hex, :scrivener, "1.2.1", "4d50f21b5c43cc88d072762584f6e49e206901d7d36007928f156f2e974eec4a", [:mix], [{:postgrex, ">= 0.0.0", [hex: :postgrex, optional: true]}, {:ecto, "~> 1.1", [hex: :ecto, optional: false]}]},
  "xain": {:hex, :xain, "0.5.3", "0696bf6db7697690f620adf59bd7ced4e4e9ae5eac3240a2a81eae3f93f5ddfe", [:mix], []}}
```

**Comment by smpallen99** [comment]
@erikmueller I just tried https://github.com/smpallen99/ex_admin_demo/tree/pre_themed with the same dependency versions you posted above. Works fine. So, I suggest you review that solution and see if you have setup project the same?

If you still can't get it working, I can take a look at your project. If so, please post a link to your source. 

Either way, would be great to hear what you find out. Thanks....Steve

**Comment by erikmueller** [comment]
Now I refactored some stuff, switched machines and the error is gone. Sorry that I cannot provide any inside what may have caused it. And after stumbling upon https://github.com/stavro/arc/issues/59 I finally have ExAdmin and Arc working.

**Comment by smpallen99** [comment]
@erikmueller Glad you got it working 👍
