### ISSUE TITLE
Relationship with empty (nil) 'name' field throws exception

### ISSUE THREAD

**Issue by tomjoro** [smpallen99/ex_admin#134]
If a parent object in a relationship has a 'name' field, then it can't be nil in database, otherwise an exception is raised during rendering. 
```
User
  has_many :accounts, Account

Account 
  belongs_to :user, User
```

If User has a 'name' field then it can't be nil in database. Triggered from line 114 in filter.ex
```
            option name, [{:value, "#{id}"} | selected]
```
In this case name is nil.

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Xain.Helpers.id_and_class_shortcuts/2
        lib/xain/helpers.ex:41: Xain.Helpers.id_and_class_shortcuts(nil, [value: "1"])
        lib/ex_admin/themes/admin_lte2/filter.ex:114: anonymous fn/3 in ExAdmin.Theme.AdminLte2.Filter.build_field/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/themes/admin_lte2/filter.ex:112: ExAdmin.Theme.AdminLte2.Filter.build_field/3
        lib/ex_admin/filter.ex:60: anonymous fn/4 in ExAdmin.Filter.check_and_build_association/3
        (elixir) lib/enum.ex:2462: Enum.do_find/3
        lib/ex_admin/themes/admin_lte2/filter.ex:72: ExAdmin.Theme.AdminLte2.Filter.build_field/3
        lib/ex_admin/themes/admin_lte2/filter.ex:21: anonymous fn/4 in ExAdmin.Theme.AdminLte2.Filter.theme_filter_view/5
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/themes/admin_lte2/filter.ex:21: ExAdmin.Theme.AdminLte2.Filter.theme_filter_view/5
        web/templates/layout/admin_lte2.html.eex:57: ExAdmin.LayoutView."admin_lte2.html"/1
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
```

**Comment by romul** [comment]
@tomjoro Thank you for the detailed report. I've added test for this case. So we will fix it soon )

**Comment by tomjoro** [comment]
Thanks, ex_admin is a super project. I can take a look at helping fix some of these issues also.

**Comment by romul** [comment]
@tomjoro I could imagine possible solution, but need more time to check..

```elixir
  # lib/ex_admin/themes/admin_lte2/filter.ex
  def build_field({name, %Ecto.Association.BelongsTo{related: assoc, owner_key: owner_key}}, q, _) do
    id = "q_#{owner_key}"
    if assoc.__schema__(:type, :name) do
      repo = Application.get_env :ex_admin, :repo
      resources = repo.all assoc
      selected_key = case q["#{owner_key}_eq"] do
        nil -> nil
        val -> val
      end
      div ".form-group" do
        title = humanize(name) |> String.replace(" Id", "")
        label ".label #{title}", for: "q_#{owner_key}"
        select "##{id}.form-control", [name: "q[#{owner_key}_eq]"] do
          option "Any", value: ""
          for r <- resources do
            id = ExAdmin.Schema.primary_key(r)
            name = ExAdmin.Helpers.display_name(r)
            selected = if "#{id}" == selected_key, do: [selected: :selected], else: []
            option name, [{:value, "#{id}"} | selected]
          end
        end
      end
    end
  end
```

**Comment by smpallen99** [comment]
@romul What would happen if we change `Xain. id_and_class_shortcuts` to work with nil? Since its just trying class and id, I don't see an issue allowing it to handle nil. Do you think that would resolve the issue?

**Comment by romul** [comment]
@smpallen99 I totally argee that nil, integer, boolean, etc. should not raise exception. Take a look at my proposal at https://github.com/smpallen99/ex_admin/issues/29
`id_and_class_shortcuts` is internal function, so it could stay as is. But use of `ensure_valid_contents` could provide much better user experience.
