### ISSUE TITLE
index macro fails when following form macro

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/ex_admin#169]
Create a resource and in the register resource block, customize the form page followed by a custom index page. Get error like:

```
== Compilation error on file web/admin/contact.ex ==
** (CompileError) web/admin/contact.ex:26: undefined function index/1
    expanding macro: ExAdmin.Register.register_resource/2
    web/admin/contact.ex:4: ContactDemo.ExAdmin.Contact (module)
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by smpallen99** [comment]
Work around. Create index first, followed by form
