### ISSUE TITLE
no function clause matching in ExAdmin.AdminLte2.LayoutView.build_menu_icon/1

### ISSUE THREAD

**Issue by andrewcottage** [smpallen99/ex_admin#190]
When trying to add a link to the actions menu I use this code:
```
defmodule Houser.ExAdmin.Facility do
  use ExAdmin.Register
  require ExAdmin.Register

  register_resource Houser.Facility do
    batch_actions false
    actions :all, []
    action_item :index, fn(r) ->
      ExAdmin.Register.link_to "Backup Now", "/admin/backuprestores/backup"
    end

    scope :with_auction, fn(q) ->
      where(q, [f], not(is_nil(f.auction_date_and_time_1)))
    end

    scope :verified, fn(q) ->
      where(q, [f], f.verified == "Yes")
    end

  end
end

```

I get an error like this:

```
[error] #PID<0.537.0> running Houser.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /facilities
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in ExAdmin.AdminLte2.LayoutView.build_menu_icon/1
        (ex_admin) web/views/admin_lte2_view.ex:29: ExAdmin.AdminLte2.LayoutView.build_menu_icon([60, "a", " href=\"/admin/backuprestores/backup\"", 62, "Backup Now", 60, 47, "a", 62])
        (ex_admin) web/templates/themes/admin_lte2/layout/header.html.eex:66: anonymous fn/2 in ExAdmin.AdminLte2.LayoutView.header.html/1
        (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_admin) web/templates/themes/admin_lte2/layout/header.html.eex:64: ExAdmin.AdminLte2.LayoutView."header.html"/1
        (ex_admin) web/templates/layout/admin_lte2.html.eex:41: ExAdmin.LayoutView."admin_lte2.html"/1
        (phoenix) lib/phoenix/view.ex:335: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:641: Phoenix.Controller.do_render/4
        (ex_admin) web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.action/2
        (ex_admin) web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.phoenix_controller_pipeline/2
        (houser) lib/houser/endpoint.ex:1: Houser.Endpoint.instrument/4
        (houser) lib/phoenix/router.ex:261: Houser.Router.dispatch/2
        (houser) web/router.ex:1: Houser.Router.do_call/2
        (houser) lib/houser/endpoint.ex:1: Houser.Endpoint.phoenix_pipeline/1
        (houser) lib/plug/debugger.ex:93: Houser.Endpoint."call (overridable 3)"/2
        (houser) lib/houser/endpoint.ex:1: Houser.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by smpallen99** [comment]
Please try it on master using the documented approach:

```
      action_item :index, fn ->
        action_item_link "Something Special", href: "/my/custom/route"
      end
```

**Comment by andrewcottage** [comment]
That did the trick.

Thank you!
