### ISSUE TITLE
"Internal server error" when using ex_admin resources in a release built by exrm

### ISSUE THREAD

**Issue by santif** [smpallen99/ex_admin#202]
After build a release with exrm, I get "Internal server error" when I try to access to `/admin` pages (UndefinedError due to ex_admin dependencies not included in the release by exrm).
I'm not sure if this issue is related to ex_admin or exrm.

Workaround is to add the following startup applications to mix.exs:

```
:inflex, :scrivener, :scrivener_ecto, :csvlixir
```

If this is the way to go, please consider add the instructions to README.md... Thanks!

**Comment by davidqhr** [comment]
+1

The log output:

```elixir
Request: GET /admin
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Inflex.underscore/1 is undefined (module Inflex is not available)
        Inflex.underscore("Admin")
        (ex_admin) lib/ex_admin/utils.ex:93: ExAdmin.Utils.titleize/1
        (ex_admin) lib/ex_admin/navigation.ex:32: ExAdmin.Navigation.nav_link/3
        (ex_admin) lib/ex_admin/navigation.ex:24: anonymous fn/4 in ExAdmin.Navigation.nav_view/2
        (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_admin) lib/ex_admin/navigation.ex:23: ExAdmin.Navigation.nav_view/2
        (ex_admin) web/templates/themes/admin_lte2/layout/header.html.eex:58: ExAdmin.AdminLte2.LayoutView."header.html"/1
        (ex_admin) web/templates/layout/admin_lte2.html.eex:41: ExAdmin.LayoutView."admin_lte2.html"/1
```

**Comment by davidqhr** [comment]
@santif, I think this will only happen when you use exrm.

Instead of updating the README.md, I think the four missing applications that ex_admin depended should add into the mix.exs applications/1;

```elixir

defp applications(_)
  [:gettext, :phoenix, :ecto, :inflex, :scrivener, :scrivener_ecto, :csvlixir, :logger, :ex_queb, :xain]
end

```
