### ISSUE TITLE
referencing model in umbrella app

### ISSUE THREAD

**Issue by ZombieHarvester** [smpallen99/ex_admin#223]
I have ex_admin installed as a separate app in umbrella. 

Product model in Admin app
```
defmodule Admin.ExAdmin.Product do
  use ExAdmin.Register

  register_resource Core.Product do
  end
end
```

Product model in Core app
```
defmodule Core.Product do
  use Core.Schema
  import Ecto.Changeset

  schema "products" do
    field      :sku, :string
    belongs_to :account, Core.Account

    timestamps
  end
end
```

i get the following error on `/admin/products`

```
[error] #PID<0.468.0> running Admin.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /admin/products
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR (undefined_column): column a0.contract_info does not exist
        (ecto) lib/ecto/adapters/sql.ex:429: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:127: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
        lib/scrivener/paginater/ecto/query.ex:15: Scrivener.Paginater.Ecto.Query.paginate/2
        web/controllers/admin_resource_controller.ex:13: ExAdmin.AdminResourceController.index/3
        web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.action/2
        web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.phoenix_controller_pipeline/2
        (admin) lib/admin/endpoint.ex:1: Admin.Endpoint.instrument/4
        (admin) lib/phoenix/router.ex:261: Admin.Router.dispatch/2
        (admin) web/router.ex:1: Admin.Router.do_call/2
        (admin) lib/admin/endpoint.ex:1: Admin.Endpoint.phoenix_pipeline/1
        (admin) lib/plug/debugger.ex:123: Admin.Endpoint."call (overridable 3)"/2
```

But if i remove `belongs_to  :account, Core.Account` line from Product schema, then everything works fine. Same issue with `has_many` references.

'column a0.contract_info does not exist' where this is coming from?

Phoenix 1.2.1, ex_admin from github
Thanks

**Comment by smpallen99** [comment]
Can you post your Core.Account schema please.

**Comment by Yamilquery** [comment]
Same problem here.

```
defmodule Smpallen99.Team do

  use Smpallen99.Web, :model

  schema "teams" do
    field :name, :string
    has_many :cases, Smpallen99.Case, foreign_key: :hospital_id
    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name])
    |> validate_required([:name])
  end
end
```

I got:

ERROR 42703 (undefined_column): column c0.team_id does not exist
