### ISSUE TITLE
How to setup many to many?

### ISSUE THREAD

**Issue by tispratik** [smpallen99/ex_admin#25]
Hello,

I have a user model and a site model. Users can belong to many sites and a sites can have many users. So, i have a `user_site` model. When i add a user, i need to associate him/her with a site. Can you suggest how to do it? The following did not work for me.

```elixir
register_resource Myapp.User do
  form user do
    inputs do
      input user, :name
      input user, :email
    end

    inputs :user_sites do
      input user, :site_id
    end
  end
end
```

user_site.ex
```elixir
defmodule Myapp.UserSite do
  use Myapp.Web, :model

  schema "user_sites" do
    timestamps

    belongs_to :user, Myapp.User
    belongs_to :site, Myapp.Site
  end
end
```

**Comment by smpallen99** [comment]
Try the following:

```elixir
form user do
  inputs do
    input user, :name
    input user, :email
  end
  inputs :sites, as: check_boxes, collection: MyApp.User.sites
end
```

**Comment by tispratik** [comment]
Thanks @smpallen99 I am getting the following error:

```Request: POST /admin/users
** (exit) an exception was raised:
    ** (KeyError) key :assoc not found in: %Ecto.Association.Has{cardinality: :many, defaults: [], field: :user_sites, on_cast: :changeset, on_delete: :nothing, on_replace: :raise, owner: Myapp.User, owner_key: :id, queryable: Myapp.UserSite, related: Myapp.UserSite, related_key: :user_id}
        lib/ex_admin/repo.ex:302: ExAdmin.Repo.get_assoc_join_model/2
        lib/ex_admin/repo.ex:312: ExAdmin.Repo.get_assoc_model/2
        lib/ex_admin/repo.ex:153: ExAdmin.Repo.do_collection/2
        lib/ex_admin/repo.ex:149: anonymous fn/3 in ExAdmin.Repo.insert_or_update_collection/2
        (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/repo.ex:49: ExAdmin.Repo.changeset_collection/3
        web/controllers/admin_controller.ex:196: ExAdmin.AdminController.create/2
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (myapp) lib/phoenix/router.ex:255: Myapp.Router.dispatch/2
        (myapp) web/router.ex:1: Myapp.Router.do_call/2
        (myapp) lib/myapp/endpoint.ex:1: Myapp.Endpoint.phoenix_pipeline/1
        (myapp) lib/plug/debugger.ex:92: Myapp.Endpoint."call (overridable 3)"/2
        (myapp) lib/phoenix/endpoint/render_errors.ex:34: Myapp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4```

And the form data submitted is:
```
[debug] Processing by ExAdmin.AdminController.create/2
  Parameters: %{"_csrf_token" => "foo", "commit" => "Create User", "resource" => "users", "user" => %{"email" => "t@t.com", "name" => "Prats", "site_ids" => ["", "1"]}, "utf8" => "✓"}
```

Seems like there is an empty site as well.

**Comment by smpallen99** [comment]
Looks like Ecto changed their internals. I'll try to get some time this evening to look at it. 

Steve

**Comment by tispratik** [comment]
Great, thanks!

**Comment by smpallen99** [comment]
Updated master for latest Ecto 1.1 and pushed a fix for this issue. Also added the repo I used to test it. 

https://github.com/smpallen99/admin_demo

**Comment by tispratik** [comment]
Great, thanks Steve. I will test it out this evening.

**Comment by tispratik** [comment]
That works! Thanks a lot for fixing it.
