### ISSUE TITLE
{:array, :map} datatype crashed for Ecto field :xxx, {:array, :map}, default: []

### ISSUE THREAD

**Issue by peterwillcn** [smpallen99/ex_admin#332]
In a schema with a field defined as

 **field :forecast_times, {:array, :map}, default: []**

I get this error if I try to view it in ExAdmin:

**(RuntimeError) Can't render map without schema :forecast_times**

```[info] GET /admin/datasets/new
[debug] Processing by ExAdmin.AdminResourceController.new/2
  Parameters: %{"resource" => "datasets"}
  Pipelines: [:browser]
[error] %RuntimeError{message: "Can't render map without schema :forecast_times"}
[error] [{ExAdmin.Form, :get_schema, 2, [file: 'lib/ex_admin/form.ex', line: 913]}, {ExAdmin.Form, :build_item, 5, [file: 'lib/ex_admin/form.ex', line: 664]}, {ExAdmin.Form, :"-build_item/5-fun-14-", 6, [file: 'lib/ex_admin/form.ex', line: 905]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1755]}, {ExAdmin.Form, :"-build_item/5-fun-15-", 5, [file: 'lib/ex_admin/form.ex', line: 902]}, {ExAdmin.Theme.ActiveAdmin.Form, :form_box, 3, [file: 'lib/ex_admin/themes/active_admin/form.ex', line: 152]}, {ExAdmin.Form, :"-build_main_block/4-fun-0-", 6, [file: 'lib/ex_admin/form.ex', line: 552]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1755]}, {ExAdmin.Form, :build_main_block, 4, [file: 'lib/ex_admin/form.ex', line: 550]}, {ExAdmin.Theme.ActiveAdmin.Form, :build_form, 6, [file: 'lib/ex_admin/themes/active_admin/form.ex', line: 26]}, {ExAdmin.AdminResourceController, :new, 3, [file: 'web/controllers/admin_resource_controller.ex', line: 74]}, {ExAdmin.AdminResourceController, :action, 2, [file: 'web/controllers/admin_resource_controller.ex', line: 1]}, {ExAdmin.AdminResourceController, :phoenix_controller_pipeline, 2, [file: 'web/controllers/admin_resource_controller.ex', line: 1]}, {LongrunData.Endpoint, :instrument, 4, [file: 'lib/longrun_data/endpoint.ex', line: 1]}, {LongrunData.Router, :dispatch, 2, [file: 'lib/phoenix/router.ex', line: 261]}, {LongrunData.Router, :do_call, 2, [file: 'web/router.ex', line: 1]}, {LongrunData.Endpoint, :phoenix_pipeline, 1, [file: 'lib/longrun_data/endpoint.ex', line: 1]}, {LongrunData.Endpoint, :"call (overridable 3)", 2, [file: 'lib/plug/debugger.ex', line: 123]}, {LongrunData.Endpoint, :call, 2, [file: 'lib/longrun_data/endpoint.ex', line: 1]}, {Plug.Adapters.Cowboy.Handler, :upgrade, 4, [file: 'lib/plug/adapters/cowboy/handler.ex', line: 15]}]
[info] Sent 500 in 21ms
[error] #PID<0.3019.0> running LongrunData.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /admin/datasets/new
** (exit) an exception was raised:
    ** (RuntimeError) Can't render map without schema :forecast_times
        lib/ex_admin/form.ex:913: ExAdmin.Form.get_schema/2
        lib/ex_admin/form.ex:664: ExAdmin.Form.build_item/5
        lib/ex_admin/form.ex:905: anonymous fn/6 in ExAdmin.Form.build_item/5
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/form.ex:902: anonymous fn/5 in ExAdmin.Form.build_item/5
        lib/ex_admin/themes/active_admin/form.ex:152: ExAdmin.Theme.ActiveAdmin.Form.form_box/3
        lib/ex_admin/form.ex:552: anonymous fn/6 in ExAdmin.Form.build_main_block/4
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/form.ex:550: ExAdmin.Form.build_main_block/4
        lib/ex_admin/themes/active_admin/form.ex:26: ExAdmin.Theme.ActiveAdmin.Form.build_form/6
        web/controllers/admin_resource_controller.ex:74: ExAdmin.AdminResourceController.new/3
        web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.action/2
        web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.phoenix_controller_pipeline/2
        (longrun_data) lib/longrun_data/endpoint.ex:1: LongrunData.Endpoint.instrument/4
        (longrun_data) lib/phoenix/router.ex:261: LongrunData.Router.dispatch/2
        (longrun_data) web/router.ex:1: LongrunData.Router.do_call/2
        (longrun_data) lib/longrun_data/endpoint.ex:1: LongrunData.Endpoint.phoenix_pipeline/1
        (longrun_data) lib/plug/debugger.ex:123: LongrunData.Endpoint."call (overridable 3)"/2
        (longrun_data) lib/longrun_data/endpoint.ex:1: LongrunData.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
```

**Comment by smpallen99** [comment]
You need to define the map schema in the admin resource file. Please see docs

**Comment by peterwillcn** [comment]
Hi smpallen99
  I fixed, Thanks! ex_admin very cool!
