### ISSUE TITLE
Expected a keyword list as the second argument

### ISSUE THREAD

**Issue by stjhimy** [smpallen99/ex_admin#402]
After a simple setup I'm getting this:

```
Server: localhost:4000 (http)
Request: GET /admin/users
** (exit) an exception was raised:
    ** (ArgumentError) expected a keyword list as the second argument, got: ["<a href='/admin/users/1' class='member_link view_link' title='View'>View</a>", "<a href='/admin/users/1/edit' class='member_link edit_link' title='Edit'>Edit</a>", "<a href='/admin/users/1' class='member_link delete_link' data-confirm='Are you sure you want to delete this?' data-remote='true' data-method='delete' data-params='page=1' rel='nofollow' title='Delete'>Delete</a>"]
        (elixir) lib/keyword.ex:589: Keyword.merge/2
        lib/xain.ex:124: Xain.merge_attrs/3
        lib/xain.ex:117: Xain.build_tag/5
        lib/ex_admin/themes/admin_lte2/index.ex:188: anonymous fn/4 in ExAdmin.Theme.AdminLte2.Index.build_table_body/4
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/themes/admin_lte2/index.ex:187: anonymous fn/5 in ExAdmin.Theme.AdminLte2.Index.build_table_body/4
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        lib/ex_admin/themes/admin_lte2/index.ex:175: ExAdmin.Theme.AdminLte2.Index.build_table_body/4
        lib/ex_admin/themes/admin_lte2/index.ex:54: ExAdmin.Theme.AdminLte2.Index.paginated_collection_table/2
        lib/ex_admin/themes/admin_lte2/index.ex:156: ExAdmin.Theme.AdminLte2.Index.batch_action_form/6
        lib/ex_admin/themes/admin_lte2/index.ex:14: ExAdmin.Theme.AdminLte2.Index.wrap_index_grid/1
        (my_app) lib/ex_admin/index.ex:158: MyApp.ExAdmin.User.index_view/3
        web/controllers/admin_resource_controller.ex:26: ExAdmin.AdminResourceController.index/3
        web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.action/2
        web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.phoenix_controller_pipeline/2
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.plug_builder_call/2
        (my_app) lib/haitracker/endpoint.ex:1: MyApp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
```

Versions:
phoenix: 1.3
ex_admin: master branch

Something wrong on the configuration or a new bug?

Thanks.

**Comment by bsidoruk** [comment]
`config :xain, :after_callback, {Phoenix.HTML, :raw}`
Needs to be added to your config file. It should have been added when you ran admin.install but if you set up manually you would have missed it
