### ISSUE TITLE
function [ProjectName].ExAdmin.Dashboard.__struct__/0 is undefined (module [ProjectName].ExAdmin.Dashboard is not available)

### ISSUE THREAD

**Issue by siriusdely** [smpallen99/ex_admin#412]
Please help...

`Phoenix v1.3.0`:

```
Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2
```

`mix.exs`:

```
{:ex_admin, github: "smpallen99/ex_admin"}
```

`config.exs`:

```
config :ex_admin,
  repo: Syrilo.Repo,
  module: Syrilo.Web,
  modules: [
    Syrilo.ExAdmin.Dashboard,
  ]

config :xain, :after_callback, {Phoenix.HTML, :raw}
```

traces:

```
[error] #PID<0.724.0> running [ProjectNameWeb].Endpoint terminated
Server: localhost:4000 (http)
Request: GET /admin
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function [ProjectName].ExAdmin.Dashboard.__struct__/0 is undefined (module [ProjectName].ExAdmin.Dashboard is not available)
        [ProjectName].ExAdmin.Dashboard.__struct__()
        (ex_admin) lib/ex_admin.ex:220: anonymous fn/2 in ExAdmin.get_registered/0
        (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_admin) lib/ex_admin.ex:219: ExAdmin.get_registered/0
        (ex_admin) web/ex_admin/controller.ex:14: ExAdmin.Controller.get_registered_by_controller_route/1
        (ex_admin) web/ex_admin/controller.ex:5: ExAdmin.Controller.get_registered_by_controller_route!/2
        (ex_admin) web/controllers/admin_controller.ex:11: ExAdmin.AdminController.page/2
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        ([ProjectName]) lib/syrilo_web/endpoint.ex:1: SyriloWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        ([ProjectName]) lib/syrilo_web/endpoint.ex:1: SyriloWeb.Endpoint.plug_builder_call/2
        ([ProjectName]) lib/plug/debugger.ex:99: SyriloWeb.Endpoint."call (overridable 3)"/2
        ([ProjectName]) lib/syrilo_web/endpoint.ex:1: SyriloWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/sirius/Elixir/syrilo/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by siriusdely** [comment]
oops, there is similar issue with solution already https://github.com/smpallen99/ex_admin/issues/399
