### ISSUE TITLE
phx-1.3.0 release Router.Helpers.admin_path/3 is undefined (module Bulldozer.Router.Helpers is not available)

### ISSUE THREAD

**Issue by peterwillcn** [smpallen99/ex_admin#419]
{:ex_admin, github: "smpallen99/ex_admin", branch: "phx-1.3"}
```
[debug] Processing with ExAdmin.AdminController.dashboard/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 500 in 176ms
[error] #PID<0.664.0> running ProjectWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /admin
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Project.Router.Helpers.admin_path/3 is undefined (module Project.Router.Helpers is not available)
        Project.Router.Helpers.admin_path(Project.Endpoint, :page, "dashboard")
        (ex_admin) lib/ex_admin/navigation.ex:32: ExAdmin.Navigation.nav_link/3
        (ex_admin) lib/ex_admin/navigation.ex:25: anonymous fn/4 in ExAdmin.Navigation.nav_view/2
        (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_admin) lib/ex_admin/navigation.ex:24: ExAdmin.Navigation.nav_view/2
        (ex_admin) web/templates/themes/active_admin/layout/header.html.eex:5: ExAdmin.ActiveAdmin.LayoutView."header.html"/1
        (ex_admin) web/templates/layout/active_admin.html.eex:30: ExAdmin.LayoutView."active_admin.html"/1
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (Project) lib/Project_web/endpoint.ex:1: ProjectWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (Project) lib/Project_web/endpoint.ex:1: ProjectWeb.Endpoint.plug_builder_call/2
        (Project) lib/plug/debugger.ex:99: ProjectWeb.Endpoint."call (overridable 3)"/2
        (Project) lib/Project_web/endpoint.ex:1: ProjectWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /use/work/heri/Project/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by peterwillcn** [comment]
Solved ....LOL
```
config :ex_admin,
  repo: MyProject.Repo,
  module: MyProjectWeb,    # NOT MyProject.Web ! LOL.......LOL
```
And, run mix do deps.clean -all, deps.get, deps.compile
