### ISSUE TITLE
Ambigious link_to

### ISSUE THREAD

**Issue by Gazler** [smpallen99/ex_admin#70]
I have just upgraded from a previous version (https://github.com/smpallen99/ex_admin/commits/700b3259b386b1143aec731f8e271f419291f215)

I am now getting the following error on compilation:

```
** (CompileError) lib/ex_admin/show.ex:29: function link_to/2 imported from both ExAdmin.Utils and ExAdmin.Register, call is ambiguous
    expanding macro: ExAdmin.Register.column/2
    lib/ex_admin/show.ex:28: VoicelayerAdmin.ExAdmin.App.show_view/2
    expanding macro: ExAdmin.Show.table_for/2
    lib/ex_admin/show.ex:27: VoicelayerAdmin.ExAdmin.App.show_view/2
    expanding macro: ExAdmin.Show.panel/2
    lib/ex_admin/show.ex:26: VoicelayerAdmin.ExAdmin.App.show_view/2
    expanding macro: Xain.markup/1
    lib/ex_admin/show.ex:60: VoicelayerAdmin.ExAdmin.App.show_view/2
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

The cause is something like:

```elixir
    index do
      column :id
      column :name
      column :inserted_at
      column "Actions", fn (account) ->
        [
         link_to("View", Helpers.admin_path(conn, :show, :accounts, account), class: "member_link"),
         link_to("Edit", Helpers.admin_path(conn, :edit, :accounts, account), class: "member_link")
        ] |> Phoenix.HTML.html_escape()
      end
    end
```

**Comment by Gazler** [comment]
I can fix it by explicitly specifying `ExAdmin.Utils.link_to`, however it seems like only one should be exported after calling `use ExAdmin.Register`.

**Comment by Gazler** [comment]
Just realised I can do:

```elixir
a("Edit", href: Helpers.admin_path(conn, :edit, :accounts, account), class: "member_link"))
```
