### ISSUE TITLE
Add fields doesn't work with has_many in form

### ISSUE THREAD

**Issue by bsidoruk** [smpallen99/ex_admin#89]
When using nested attributes in a form with the has_many command, the 'add' button does not append the blank fields to the form.  If a nested attribute already exists, the forms do appear with the correct data filled in, but trying to update them leads to the error:
    
    protocol Ecto.Queryable not implemented for :error, the given module does not exist

**Comment by smpallen99** [comment]
@bsidoruk What version of ex_admin are you using. It is mostly working on the `themes` branch. I just tested it in chrome and safari on http://demo2.exadmin.info with success except for one issue. If you add a phone number, the delete button is not work. So, I'll have to take a look at that. I don't expect it to work on v0.7.2 or on master. 

I'm working issue #82 right now. Once I have the complete, I'm going to publish v0.7.4 in hex, and merge the themes stuff into master (which has Ecto 2.0 support.

**Comment by bsidoruk** [comment]
I'm also using the themes branch.  The add phone number example worked for me as well, but for some reason it doesn't appear to be working with my app.  I've formatted my form the same as your example in the docs.  Also, in regard to a using a collection for a select tag, is there a way to specify a different value  for an option than the key? Like you can do in Phoenix.HTML
    
select(form, :role, ["Admin": "admin", "User": "user"])

**Comment by smpallen99** [comment]
The http://demo2.exadmin.info app has an example of selecting roles. However, it is a many-to-many example using a join table. Couple questions:
* is your role field a string?
* are you trying to do a nested attributes (like the phone_numbers example?)
* could you post the relevant parts of your models?

Steve

**Comment by bsidoruk** [comment]
Yes the the field is a string, and I'm nesting it like the phone_numbers example.  It seems from briefly looking at your code, that it should be compatible with binary tuples, but I'm getting an error with the string key:
    
    protocol String.Chars not implemented for {:"Admin", "admin"}
    
In regards to the nested fields, my relation is a one-to-many, so maybe that is the difference.  However I'm not sure why it should affect the fields from getting appended.  Using web inspector I am able to see that there is a different div:
    <div class="box has_many_fields">
in my app rather than
    <div class="box"> 
thats in your example app.

**Comment by smpallen99** [comment]
Brad, I'm still trying to wrap my head around this so I can write a test case and give you a fix :)

So, role is a string field. My assumption then, is that there is no Role schema(model). But then, I don't see how you could use nested attributes approach (generate a new role  in, lets say, the User form) since there would be no way to reuse that role for another User. 

Or perhaps you do have a role table without an id, in which case you have the primary key in the role table as the name of the role. 

Perhaps the best way is to post example models that I can use in a test case. 

I will say that when I designed nested attributes, I assumed they were a many-to-many relationship. I did not account for the scenario of a one-to-many relationship. But that is a valid use case and an over site on my part. Posting example models will help me ensure that my design fixes your issue :)

**Comment by bsidoruk** [comment]
I was using role as an example from the Phoenix.HTML docs.  What I'm using is something more like a User has many Addresses, so it is a one to many relationship.  So I am trying to set it up something like this in admin/user.ex:
    
    form user do
      inputs "Addresses" do
        has_many user, :addresses, fn(a) ->
          input a, :street
          input a, :phone_number
          input a, :type, collection: Address.types
        end
      end
    
Where Address.types would be a defined list of key-value pairs for a select tag, where: ["Work": "work"] would give and option "Work" that has the value "work"

**Comment by smpallen99** [comment]
Perfect, that should give me enough to test it out... I'll take a quick look now.

**Comment by smpallen99** [comment]
Ok, can reproduce the issue with the following models:

```
  schema "users" do
    field :name, :string
    has_many :addresses, NestAddr.Address
  end
```
```
  schema "addresses" do
    field :street, :string
    field :phone_number, :string
    field :type, :string
    belongs_to :user, NestAddr.User
  end
```

This will take some work since I did not account for the case of simple has_many relationship. I will need to update view generators as well as the repo code that reflects on the relationship and creates the model...

**Comment by bsidoruk** [comment]
Thanks so much for checking this out

**Comment by smpallen99** [comment]
I have has_many working for one-to_many relationship. Need to do a bit more testing before I push it. 

I'll add the collection as a tuple request under issue #91 that I just created.

**Comment by bsidoruk** [comment]
That's awesome. Thanks for getting to that so quick

**Comment by smpallen99** [comment]
@bsidoruk Quick update... I did get the update case working, but ran into some big issues with create. Its going to take a big refactor to get working properly. I was working on the ecto 1.1 branch. However, with all the changes in ecto 2.0 around support for many-to-many associations, I think I'm going to do this work in support for ecto 2.0 only. 

Its going to take me a few more days to complete this. Sorry for the delay...
Steve

**Comment by bsidoruk** [comment]
No worries.  That works for me. Thanks for working on that.

**Comment by smpallen99** [comment]
Started prototyping a refactor of `ExAdmin.Repo`. It will allow support for this as well as a much simplified design. Still not working...

@romul This may have an impact on the stuff your are doing. Can you take a look at my `repo_refactored` branch, specifically the `Repo2` and `Changeset2` modules. I also have some tests in `repo2_test.exs`. I'm going to tackle `has_many , through:` next, then  `many_to_many` after that. 

_Note: this refactor will be for Ecto 2 only..._

**Comment by romul** [comment]
@smpallen99 Ok, I'll take a look at the weekend )

**Comment by sdn90** [comment]
Is this working in master?

I'm getting this error:
```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :error.__struct__/0 is undefined (module :error is not available)
        :error.__struct__()
        anonymous fn/8 in ExAdmin.Form.build_item/5
        lib/ex_admin/themes/admin_lte2/form.ex:123: ExAdmin.Theme.AdminLte2.Form.build_inputs_has_many/3
        lib/ex_admin/form.ex:727: ExAdmin.Form.build_item/5
        lib/ex_admin/form.ex:813: anonymous fn/6 in ExAdmin.Form.build_item/5
        (elixir) lib/enum.ex:1622: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/form.ex:812: anonymous fn/5 in ExAdmin.Form.build_item/5
        lib/ex_admin/themes/admin_lte2/form.ex:136: ExAdmin.Theme.AdminLte2.Form.form_box/3
        lib/ex_admin/form.ex:507: anonymous fn/6 in ExAdmin.Form.build_main_block/4
        (elixir) lib/enum.ex:1622: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/form.ex:505: ExAdmin.Form.build_main_block/4
        lib/ex_admin/themes/admin_lte2/form.ex:23: ExAdmin.Theme.AdminLte2.Form.build_form/5
        web/controllers/admin_resource_controller.ex:203: ExAdmin.AdminResourceController.new/3
        web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.action/2
        web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.phoenix_controller_pipeline/2
        (api) lib/api/endpoint.ex:1: Api.Endpoint.instrument/4
        (api) lib/phoenix/router.ex:261: Api.Router.dispatch/2
        (api) web/router.ex:1: Api.Router.do_call/2
        (api) lib/api/endpoint.ex:1: Api.Endpoint.phoenix_pipeline/1
        (api) lib/plug/debugger.ex:93: Api.Endpoint."call (overridable 3)"/2
```

With this code (modified from example in docs):

```elixir
# ...
  register_resource Api.Album do
    form album do
      inputs do
        input album, :title
      end
      inputs "Tracks" do
        has_many mixtape, :tracks, fn (t) ->
          input t, :number
        end
      end
    end
# ...
```

**Comment by smpallen99** [comment]
@sdn90 I will need to see your models/schemas to look at it. Also, need your ecto version....

**Comment by sdn90** [comment]
@smpallen99 Sorry, it was late and forgot to add those.

Using Ecto 2.0

Model  
```elixir
  schema "albums" do
    field :title, :string
    field :cover_image, :string
    has_many :tracks, Api.Track

    timestamps()
  end
```

**Comment by smpallen99** [comment]
I believe this only works for has_many through: .. relationships at this time.

**Comment by romul** [comment]
@smpallen99 I'll take a look at this issue this week.

**Comment by vraravam** [comment]
@smpallen99 - any updates on this? I have a simple belongs_to <-> has_many (and NOT a has_many_through) relationship. I'm using the latest master branch of ex_admin - and this doesn't seem to work
